name: Run PowerShell Script

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  run-powershell:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run PowerShell script
        run: |
          pwsh -File script.ps1
        shell: pwsh