name: Run PowerShell Script

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  run-powershell:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run PowerShell script
        env:
          TO_USERNAME : ${{secrets.TO_USERNAME}}
          MAIL_USERNAME : ${{secrets.MAIL_USERNAME}}
          MAIL_PASSWORD : ${{secrets.MAIL_PASSWORD}}
        run: pwsh -File script.ps1